framework:
    messenger:
        failure_transport: failed
        transports:
            amqp:
                dsn: '%env(MESSENGER_AMQP_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    queues:
                        user_create_queue:
                            binding_keys:
                                - user.create
                    exchange:
                        name: blog_topic_exchange
                        type: topic
                retry_strategy:
                    max_retries: 1
                    delay: 1000
            failed:
                dsn: '%env(MESSENGER_DOCTRINE_TRANSPORT_DSN)%'
                options:
                    table_name: failed_messages

        routing:
            'App\Message\AsyncMessageInterface': amqp

