monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        message_handler:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/message_handler.log"
            level: debug
            channels: ["message_handler"]
        blog_mailer:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/blog_mailer.log"
            level: debug
            channels: ["blog_mailer"]
